# Generated by Django 5.0.7 on 2024-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsessionsapp', '0002_athlete_remove_set_user_remove_session_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='preferred_category',
            field=models.CharField(blank=True, choices=[('Bodybuilding', 'Bodybuilding'), ('Calisthenics', 'Calisthenics'), ('Power Lifting', 'Powerlifting'), ('Hybrid', 'Hybrid')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Bodybuilding', 'Bodybuilding'), ('Calisthenics', 'Calisthenics'), ('Power Lifting', 'Powerlifting'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='main_muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Delts', 'Deltoids'), ('Quads', 'Quads'), ('Hamstrings', 'Hamstrings'), ('Legs', 'Legs'), ('Abs', 'Abs')], max_length=50),
        ),
    ]
