# Generated by Django 5.0.7 on 2024-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsessionsapp', '0003_alter_athlete_preferred_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='rest_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
