# Generated by Django 5.0.7 on 2024-07-21 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('main_muscle_group', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=1023)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('encrypted_pw', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('preferred_category', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('profile_picture_url', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsessionsapp.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsessionsapp.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsessionsapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsessionsapp.user'),
        ),
    ]
